import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-full h-screen bg-slate-950 flex items-center justify-center`}>
        <main className='flex flex-col items-center justify-start w-96 h-3/4 bg-slate-50 bg-opacity-10 rounded-2xl shadow-md'>
          {children}
        </main>
      </body>
    </html>
  )
}
